Repository man-group/ArcticDB, pull requests merged in 2023-11, with the labels that each got.

#864 feat: Allow `row_range` to be treated as a clause
  cpp/arcticdb/column_store/chunked_buffer.cpp
  cpp/arcticdb/column_store/memory_segment_impl.hpp
  cpp/arcticdb/pipeline/frame_slice.hpp
  cpp/arcticdb/pipeline/query.hpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/version/python_bindings.cpp
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_query_builder.py
  python/tests/unit/arcticdb/version_store/test_row_range.py
Labels: enhancement

#997 941 self hosted runners for ci
  .github/actions/run_local_pytest/action.yml
  .github/workflows/analysis_workflow.yml
  .github/workflows/build.yml
  .github/workflows/build_steps.yml
  .github/workflows/build_with_conda.yml
  .github/workflows/ec2_runner_jobs.yml
  build_tooling/parallel_test.sh
  build_tooling/vcpkg_caching.sh
  environment_unix.yml
  python/arcticdb/util/test.py
  python/arcticdb/version_store/_store.py
  python/tests/conftest.py
  python/tests/hypothesis/arcticdb/test_append.py
  python/tests/hypothesis/arcticdb/test_hypothesis_version_store.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/test_arctic_move_storage.py
  python/tests/integration/arcticdb/test_lmdb.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_aggregation.py
  python/tests/unit/arcticdb/version_store/test_append.py
  python/tests/unit/arcticdb/version_store/test_engine.py
  python/tests/unit/arcticdb/version_store/test_filtering_dynamic.py
  python/tests/util/mark.py
  python/tests/util/storage_test.py
  setup.cfg
Labels: enhancement

#1027 Make dependency of pymongo optional in running
  cpp/arcticdb/python/python_module.cpp
  environment_unix.yml
  python/arcticdb/adapters/mongo_library_adapter.py
  python/tests/integration/arcticdb/test_arctic.py
  setup.cfg
Labels: enhancement

#1063 Add a fallback to free GH runners, when there is a problem with the self-hosted ones
  .github/workflows/build.yml
  .github/workflows/build_steps.yml
  .github/workflows/build_with_conda.yml
  .github/workflows/ec2_runner_jobs.yml
Labels: bug

#1064 Add preliminary change for slowdown error test
  cpp/proto/arcticc/pb2/storage.proto
Labels: enhancement

#1049 fix: Empty column handling improvements
  cpp/arcticdb/entity/merge_descriptors.cpp
  cpp/arcticdb/entity/types.hpp
  cpp/arcticdb/pipeline/write_frame.cpp
  cpp/arcticdb/python/python_to_tensor_frame.cpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/version_core.cpp
  python/arcticdb/version_store/_normalization.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_deletion.py
  python/tests/nonreg/arcticdb/version_store/test_nonreg_specific.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
  python/tests/util/storage_test.py
Labels: bug

#1090 Pin all our Github actions deps
  .github/workflows/analysis_workflow.yml
  .github/workflows/build_steps.yml
  .github/workflows/build_with_conda.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_publish.yml
  .github/workflows/ec2_runner_jobs.yml
  .github/workflows/persistent_storage.yml
  .github/workflows/publish.yml
Labels: bug

#1079 fix: Empty column handling improvements
  cpp/arcticdb/entity/merge_descriptors.cpp
  cpp/arcticdb/entity/types.hpp
  cpp/arcticdb/pipeline/write_frame.cpp
  cpp/arcticdb/python/python_to_tensor_frame.cpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/version_core.cpp
  python/arcticdb/version_store/_normalization.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_deletion.py
  python/tests/nonreg/arcticdb/version_store/test_nonreg_specific.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
  python/tests/util/storage_test.py
Labels: bug

#1103 small getting-started-docs tweaks
  docs/mkdocs/docs/index.md
Labels: documentation
