Repository man-group/ArcticDB, pull requests merged in 2023-09, with the labels that each got.

#822 Fix the dependencies for the can_merge step
  .github/workflows/build.yml
Labels: bug

#784 Analysis workflow (#783)
  .github/workflows/analysis_workflow.yml
  cpp/CMakeLists.txt
  python/tests/stress/arcticdb/version_store/test_stress_version_map_compact.py
  setup.cfg
Labels: enhancement

#833 Improve handling on obsolete S3 option "force_uri_lib_config"
  python/arcticdb/adapters/s3_library_adapter.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: bug

#804 fix: Empty column normalization with `EMPTYVAL`
  cpp/arcticdb/entity/types.cpp
  cpp/arcticdb/entity/types.hpp
  cpp/arcticdb/python/python_to_tensor_frame.cpp
  cpp/arcticdb/stream/index.hpp
  cpp/arcticdb/version/schema_checks.hpp
  python/arcticdb/version_store/_normalization.py
  python/tests/unit/arcticdb/version_store/test_empty_writes.py
Labels: enhancement

#828 Issue #812 Non-functional library manager refactor
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/storage/library_manager.cpp
  cpp/arcticdb/storage/library_manager.hpp
Labels: refactor

#853 Make azure test run on conda build
  .github/workflows/build_with_conda.yml
  cpp/arcticdb/storage/storage_factory.hpp
  cpp/arcticdb/toolbox/python_bindings.cpp
  environment_unix.yml
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/test_arctic_batch.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_deletion.py
  python/tests/scripts/test_update_storage.py
  python/tests/stress/arcticdb/version_store/test_stress_delete.py
  python/tests/stress/arcticdb/version_store/test_stress_multicolumn.py
Labels: enhancement

#839 Fix list versions latest only
  cpp/arcticdb/version/version_store_api.cpp
  python/tests/integration/arcticdb/test_arctic.py
Labels: bug

#874 Bugfix from 827 changes: Prevent Unnecessary Reference Decrement in PyStringWrapper Destructors
  cpp/arcticdb/pipeline/frame_utils.hpp
  cpp/arcticdb/python/python_to_tensor_frame.cpp
  cpp/arcticdb/python/python_to_tensor_frame.hpp
Labels: bug

#878 Update azure max batch size
  cpp/arcticdb/storage/azure/azure_storage-inl.hpp
Labels: bug

#539 Extra update checks
  cpp/arcticdb/async/async_store.hpp
  cpp/arcticdb/version/version_core.cpp
Labels: bug

#882 maint: Indicate the non-support of PyArrow
  environment_unix.yml
  python/arcticdb/version_store/_normalization.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
  setup.cfg
Labels: bug

#891 Add pymongo to the list of install dependencies
  python/arcticdb/adapters/mongo_library_adapter.py
  setup.cfg
  setup.py
Labels: bug

#789 Extend persistent storage tests
  .github/actions/set_persistent_storage_env_vars/action.yml
  .github/workflows/build.yml
  .github/workflows/build_steps.yml
  .github/workflows/persistent_storage.yml
  build_tooling/README.md
  build_tooling/cleanup_storage.py
  build_tooling/parallel_test.sh
  build_tooling/seed_storage.py
  build_tooling/storage_common.py
  build_tooling/verify_storage.py
  cpp/arcticdb/storage/python_bindings.cpp
  cpp/arcticdb/storage/s3/s3_storage.cpp
  cpp/arcticdb/storage/storage_override.hpp
  docs/mkdocs/docs/index.md
  python/arcticdb/version_store/helper.py
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/test_persistent_storage.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_categorical.py
  python/tests/integration/arcticdb/version_store/test_dedup.py
  python/tests/integration/arcticdb/version_store/test_deletion.py
  python/tests/integration/arcticdb/version_store/test_metadata_support.py
  python/tests/integration/arcticdb/version_store/test_pandas_support.py
  python/tests/integration/arcticdb/version_store/test_snapshot.py
  python/tests/integration/arcticdb/version_store/test_symbol_list.py
  python/tests/integration/arcticdb/version_store/test_update_with_date_range.py
  python/tests/nonreg/arcticdb/version_store/test_nonreg_specific.py
  python/tests/stress/arcticdb/version_store/test_deallocation.py
  python/tests/stress/arcticdb/version_store/test_long_running.py
  python/tests/stress/arcticdb/version_store/test_stress_append.py
  python/tests/stress/arcticdb/version_store/test_stress_delete.py
  python/tests/stress/arcticdb/version_store/test_stress_dynamic_bucketize.py
  python/tests/stress/arcticdb/version_store/test_stress_generated.py
  python/tests/stress/arcticdb/version_store/test_stress_indexing.py
  python/tests/stress/arcticdb/version_store/test_stress_multicolumn.py
  python/tests/stress/arcticdb/version_store/test_stress_version_map_compact.py
  python/tests/stress/arcticdb/version_store/test_stress_versions.py
  python/tests/unit/arcticdb/version_store/test_aggregation.py
  python/tests/unit/arcticdb/version_store/test_fork.py
  python/tests/unit/arcticdb/version_store/test_projection.py
  python/tests/util/storage_test.py
Labels: enhancement
