Repository man-group/ArcticDB, pull requests merged in 2023-07, with the labels that each got.

#533 Add test for filtering down the stringpool with Nones and NaNs retained in a string column
  python/tests/unit/arcticdb/version_store/test_filtering.py
Labels: enhancement

#589 Support negative integers in `as_of`
  cpp/arcticdb/entity/types.hpp
  cpp/arcticdb/pipeline/query.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/test/test_version_map_batch.cpp
  cpp/arcticdb/version/version_functions.hpp
  cpp/arcticdb/version/version_map.hpp
  cpp/arcticdb/version/version_map_batch_methods.hpp
  cpp/arcticdb/version/version_map_entry.hpp
  cpp/arcticdb/version/version_utils.hpp
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
Labels: enhancement

#629 Enhancement/612/read batch to catch all exceptions
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/entity/data_error.hpp
  cpp/arcticdb/pipeline/query.hpp
  cpp/arcticdb/pipeline/read_options.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/test/test_version_store.cpp
  cpp/arcticdb/version/version_map.hpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  cpp/arcticdb/version/versioned_engine.hpp
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_filtering.py
Labels: enhancement

#655 Add instructions for how to "remove" a Conda release
  docs/mkdocs/docs/technical/releasing.md
Labels: documentation

#653 Update release docs
  docs/mkdocs/docs/technical/releasing.md
Labels: documentation

#656 Change load parameter from load all to load undeleted when reading library versions
  cpp/arcticdb/version/version_functions.hpp
Labels: bug

#659 Fix negative as_of for batch methods
  cpp/arcticdb/version/version_map_batch_methods.hpp
  python/tests/integration/arcticdb/test_arctic_batch.py
Labels: bug

#623 Fix to ensure batch prune previous methods clean up index and data keys as well as version keys
  cpp/arcticdb/async/async_store.hpp
  cpp/arcticdb/storage/test/in_memory_store.hpp
  cpp/arcticdb/stream/stream_sink.hpp
  cpp/arcticdb/stream/test/mock_stores.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/test/test_version_map.cpp
  cpp/arcticdb/version/version_map_batch_methods.hpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_tasks.hpp
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
Labels: bug

#660 Minor dependency upgrades for curl and openssl
  cpp/vcpkg.json
Labels: enhancement

#676 Only log ErrorCategory::INTERNAL errors
  cpp/arcticdb/util/preconditions.hpp
Labels: bug
