Repository man-group/ArcticDB, pull requests merged in 2023-08, with the labels that each got.

#686 Docs 672: Add docstring for DataError class
  cpp/arcticdb/version/python_bindings.cpp
  docs/README.md
  docs/sphinxdocs/source/arcticdb/arcticdb.Arctic.rst
  docs/sphinxdocs/source/conf.py
  docs/sphinxdocs/source/library.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.Library.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.ReadInfoRequest.rst
  python/arcticdb/__init__.py
Labels: documentation

#596 Pass `ReadOptions` rather than individual options; Fix `as_of` with timestamp reading entire version chain
  cpp/arcticdb/pipeline/read_options.hpp
  cpp/arcticdb/storage/test/in_memory_store.hpp
  cpp/arcticdb/stream/test/stream_test_common.hpp
  cpp/arcticdb/util/test/generators.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/test/rapidcheck_version_map.cpp
  cpp/arcticdb/version/test/test_version_map.cpp
  cpp/arcticdb/version/test/test_version_map_batch.cpp
  cpp/arcticdb/version/test/test_version_store.cpp
  cpp/arcticdb/version/test/version_backwards_compat.hpp
  cpp/arcticdb/version/test/version_map_model.hpp
  cpp/arcticdb/version/version_functions.hpp
  cpp/arcticdb/version/version_map.hpp
  cpp/arcticdb/version/version_map_batch_methods.hpp
  cpp/arcticdb/version/version_map_entry.hpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  cpp/arcticdb/version/version_tasks.hpp
  cpp/arcticdb/version/version_utils.hpp
  cpp/arcticdb/version/versioned_engine.hpp
  python/arcticdb/version_store/_store.py
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_deletion.py
  python/tests/stress/arcticdb/version_store/test_stress_version_map_compact.py
  python/tests/unit/arcticdb/version_store/test_aggregation.py
  python/tests/unit/arcticdb/version_store/test_filtering.py
  python/tests/unit/arcticdb/version_store/test_query_builder.py
  python/tests/util/date.py
Labels: enhancement

#704 Bugfix 703: Restrict supported string types to type equality rather than has isinstance
  python/arcticdb/version_store/_normalization.py
Labels: bug

#486 run C++ tests for conda build / ci
  .github/workflows/build_with_conda.yml
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/util/test/gtest_utils.hpp
  cpp/arcticdb/util/test/test_bitmagic.cpp
  cpp/arcticdb/util/test/test_format_date.cpp
  cpp/arcticdb/util/test/test_storage_lock.cpp
  cpp/arcticdb/version/test/test_sorting_info_state_machine.cpp
  cpp/arcticdb/version/test/test_symbol_list.cpp
  setup.py
Labels: bug

#712 Enhancement 558+529+556: Add option to treat date_range as a clause to reduce memory usage, and so that it works with other QueryBuilder clauses
  cpp/arcticdb/column_store/column.hpp
  cpp/arcticdb/column_store/test/rapidcheck_column.cpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/version/python_bindings.cpp
  python/arcticdb/supported_types.py
  python/arcticdb/version_store/_normalization.py
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/arcticdb/version_store/processing.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_query_builder.py
Labels: enhancement

#749 Azure getting started guide
  docs/mkdocs/docs/azure.md
  docs/mkdocs/mkdocs.yml
Labels: documentation

#663 Add more info in the CI readme; Prepare var for real storage tests
  .github/workflows/README.md
  .github/workflows/build.yml
  .github/workflows/build_steps.yml
  .github/workflows/persistent_storage.yml
  build_tooling/README.md
  build_tooling/cleanup_storage.py
  build_tooling/seed_storage.py
  build_tooling/storage_common.py
  build_tooling/verify_storage.py
  python/arcticdb/version_store/helper.py
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_persistent_storage.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
Labels: enhancement

#662 conda-build: Use default compilers for macOS
  .github/workflows/build_with_conda.yml
  cpp/CMakePresets.json
  environment_unix.yml
Labels: bug

#775 Enhancement 702: Add option to create library if it does not exist when calling get_library
  python/arcticdb/adapters/arctic_library_adapter.py
  python/arcticdb/adapters/azure_library_adapter.py
  python/arcticdb/adapters/lmdb_library_adapter.py
  python/arcticdb/adapters/s3_library_adapter.py
  python/arcticdb/arctic.py
  python/arcticdb/exceptions.py
  python/arcticdb/options.py
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: enhancement

#778 Enhancement 714: Expose library methods to list symbols with staged data, and to delete staged data
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/unit/arcticdb/version_store/test_parallel.py
Labels: enhancement

#792 perf(VectorDB): parallelise top-k queries.
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/vector_db/vector_db.cpp
  cpp/arcticdb/vector_db/vector_db.hpp
  cpp/arcticdb/version/version_core.cpp
  python/tests/unit/arcticdb/version_store/test_parallel.py
  setup.py
Labels: enhancement

#795 Add dep on packaging
  environment_unix.yml
  setup.cfg
Labels: bug

#794 Enhancement 737: Support empty-type columns in QueryBuilder operations
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/column_store/memory_segment_impl.hpp
  cpp/arcticdb/column_store/test/test_memory_segment.cpp
  cpp/arcticdb/pipeline/value_set.cpp
  cpp/arcticdb/pipeline/value_set.hpp
  cpp/arcticdb/processing/aggregation.cpp
  cpp/arcticdb/processing/aggregation.hpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/operation_dispatch_unary.hpp
  cpp/arcticdb/processing/processing_unit.hpp
  cpp/arcticdb/processing/test/test_clause.cpp
  cpp/arcticdb/processing/test/test_operation_dispatch.cpp
  cpp/arcticdb/util/test/generators.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
Labels: enhancement

#800 Fix get_num_rows for NativeVersionStore
  python/arcticdb/version_store/_store.py
  python/tests/unit/arcticdb/version_store/test_api.py
Labels: bug

#713 conda-build: Adapt C++ test suite for Linux
  .github/workflows/build_with_conda.yml
Labels: enhancement
