Repository man-group/ArcticDB, pull requests merged in 2023-10, with the labels that each got.

#860 Memory backed api
  .gitignore
  cpp/arcticdb/storage/memory/memory_storage-inl.hpp
  cpp/arcticdb/storage/memory/memory_storage.cpp
  cpp/arcticdb/storage/memory/memory_storage.hpp
  cpp/arcticdb/util/test/generators.hpp
  cpp/proto/arcticc/pb2/in_memory_storage.proto
  docs/mkdocs/docs/images/LMDBConcurrency.png
  docs/mkdocs/docs/images/LMDBtmpfsDiskMemSpeeds.png
  docs/mkdocs/docs/index.md
  docs/mkdocs/docs/tutorials/lmdb_and_in_memory.md
  docs/mkdocs/mkdocs.yml
  docs/sphinxdocs/source/arcticdb/arcticdb.Arctic.rst
  docs/sphinxdocs/source/arcticdb/arcticdb.LibraryOptions.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.ArcticDuplicateSymbolsInBatchException.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.ArcticInvalidApiUsageException.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.ArcticUnsupportedDataTypeException.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.Library.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.NormalizableType.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.ReadInfoRequest.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.ReadRequest.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.SymbolDescription.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.SymbolVersion.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.VersionInfo.rst
  docs/sphinxdocs/source/library/arcticdb.version_store.library.WritePayload.rst
  python/arcticdb/adapters/in_memory_library_adapter.py
  python/arcticdb/arctic.py
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/test_in_memory.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_metadata_support.py
  python/tests/integration/arcticdb/version_store/test_pandas_support.py
  python/tests/integration/arcticdb/version_store/test_symbol_list.py
  python/tests/integration/toolbox/test_library_tool.py
  python/tests/nonreg/arcticdb/version_store/test_nonreg_specific.py
  python/tests/stress/arcticdb/version_store/test_stress_generated.py
Labels: enhancement

#931 fix: Change comparison in `test_hypothesis_{sum,mean}_agg`
  python/tests/unit/arcticdb/version_store/test_aggregation.py
Labels: bug

#916 Update storage compatibility
  README.md
Labels: documentation

#949 Fixes IFNDR issue due to mismatching inline/non-inline functions depending on the translation unit (fixes #943)
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/entity/key-inl.hpp
  cpp/arcticdb/entity/key.hpp
  cpp/arcticdb/storage/azure/azure_storage-inl.hpp
  cpp/arcticdb/storage/azure/azure_storage.cpp
  cpp/arcticdb/storage/lmdb/lmdb_storage-inl.hpp
  cpp/arcticdb/storage/lmdb/lmdb_storage.cpp
  cpp/arcticdb/storage/memory/memory_storage-inl.hpp
  cpp/arcticdb/storage/memory/memory_storage.cpp
  cpp/arcticdb/storage/mongo/mongo_storage-inl.hpp
  cpp/arcticdb/storage/mongo/mongo_storage.cpp
  cpp/arcticdb/storage/s3/nfs_backed_storage-inl.hpp
  cpp/arcticdb/storage/s3/nfs_backed_storage.cpp
  cpp/arcticdb/storage/s3/nfs_backed_storage.hpp
  cpp/arcticdb/storage/s3/s3_storage-inl.hpp
  cpp/arcticdb/storage/s3/s3_storage.cpp
  cpp/arcticdb/storage/s3/s3_storage_tool-inl.hpp
  cpp/arcticdb/storage/s3/s3_storage_tool.cpp
  cpp/arcticdb/storage/s3/s3_storage_tool.hpp
  cpp/arcticdb/util/test/test_id_transformation.cpp
Labels: bug

#927 Update documentation
  docs/mkdocs/docs/technical/contributing.md
Labels: documentation

#966 Fix storage lock implementation for Windows debug builds
  cpp/arcticdb/util/storage_lock.hpp
  cpp/arcticdb/util/test/test_storage_lock.cpp
  cpp/arcticdb/version/test/test_version_store.cpp
Labels: bug

#948 Support `count` aggregator with groupby
  cpp/arcticdb/processing/aggregation.cpp
  cpp/arcticdb/processing/aggregation.hpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/test/test_clause.cpp
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_aggregation.py
  python/tests/unit/arcticdb/version_store/test_aggregation_dynamic.py
Labels: enhancement

#945 Initial rocksdb work
  .github/workflows/build.yml
  .github/workflows/build_steps.yml
  .github/workflows/cibw_docker_image.yml
  build_tooling/prep_cpp_build.sh
  cpp/CMake/FindLZ4.cmake
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/codec/segment.hpp
  cpp/arcticdb/entity/protobufs.hpp
  cpp/arcticdb/storage/rocksdb/rocksdb_storage.cpp
  cpp/arcticdb/storage/rocksdb/rocksdb_storage.hpp
  cpp/arcticdb/storage/test/test_embedded.cpp
  cpp/proto/arcticc/pb2/proto/CMakeLists.txt
  cpp/proto/arcticc/pb2/rocksdb_storage.proto
  cpp/vcpkg.json
  environment_unix.yml
  setup.py
Labels: enhancement

#1006 Custom exception when LMDB map is full
  cpp/arcticdb/python/python_module.cpp
  cpp/arcticdb/util/error_code.hpp
  docs/mkdocs/docs/error_messages.md
  python/tests/integration/arcticdb/test_lmdb.py
Labels: enhancement

#1011 Issue #992 Throw the LMDB map full exception on put
  cpp/arcticdb/storage/lmdb/lmdb_storage.cpp
  python/tests/integration/arcticdb/test_arctic_move_storage.py
  python/tests/integration/arcticdb/test_lmdb.py
Labels: bug

#1022 Issue #1017 Only warn if the "base" LMDB env is opened twice
  cpp/arcticdb/storage/lmdb/lmdb_storage.cpp
  cpp/arcticdb/storage/lmdb/lmdb_storage.hpp
  python/tests/integration/arcticdb/test_lmdb.py
Labels: bug
