Repository man-group/ArcticDB, pull requests merged in 2023-06, with the labels that each got.

#477 Demo notebook
  docs/mkdocs/docs/images/100kBy100k.png
  docs/mkdocs/docs/images/AppendExample.png
  docs/mkdocs/docs/images/AppendExample306x224.png
  docs/mkdocs/docs/images/ArcticDBConcepts.png
  docs/mkdocs/docs/images/ArcticDBConcepts1195x585.png
  docs/mkdocs/docs/images/ArcticDBConcepts956x468.png
  docs/mkdocs/docs/images/ArcticDBLogo.png
  docs/mkdocs/docs/images/ArcticDBLogo.svg
  docs/mkdocs/docs/images/UpdateExample.png
  docs/mkdocs/docs/images/UpdateExample306x224.png
  docs/mkdocs/docs/notebooks/ArcticDB_demo_lmdb.ipynb
  docs/mkdocs/docs/notebooks/README.md
Labels: documentation

#485 Set prune_previous_versions as False by default
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: bug

#471 Enhancement/314/refactor processing pipeline
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/async/async_store.hpp
  cpp/arcticdb/async/task_scheduler.hpp
  cpp/arcticdb/async/tasks.hpp
  cpp/arcticdb/column_store/memory_segment_impl.hpp
  cpp/arcticdb/entity/types.hpp
  cpp/arcticdb/pipeline/column_stats.cpp
  cpp/arcticdb/pipeline/query.hpp
  cpp/arcticdb/pipeline/read_pipeline.hpp
  cpp/arcticdb/processing/aggregation.cpp
  cpp/arcticdb/processing/aggregation.hpp
  cpp/arcticdb/processing/aggregation_interface.hpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/processing/execution_context.hpp
  cpp/arcticdb/processing/expression_context.hpp
  cpp/arcticdb/processing/grouper.hpp
  cpp/arcticdb/processing/processing_segment.cpp
  cpp/arcticdb/processing/processing_segment.hpp
  cpp/arcticdb/processing/test/test_clause.cpp
  cpp/arcticdb/processing/test/test_expression.cpp
  cpp/arcticdb/storage/test/in_memory_store.hpp
  cpp/arcticdb/stream/stream_source.hpp
  cpp/arcticdb/util/composite.hpp
  cpp/arcticdb/util/test/test_composite.cpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/version_core.cpp
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/processing.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_aggregation.py
  python/tests/unit/arcticdb/version_store/test_aggregation_dynamic.py
  python/tests/unit/arcticdb/version_store/test_filtering.py
  python/tests/unit/arcticdb/version_store/test_parallel.py
  python/tests/unit/arcticdb/version_store/test_projection_dynamic.py
  python/tests/unit/arcticdb/version_store/test_query_builder.py
Labels: enhancement

#516 [BREAKING API CHANGE] Rename write_batch_pickle to write_pickle_batch
  docs/sphinxdocs/source/library/arcticdb.version_store.library.Library.rst
  python/arcticdb/options.py
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: bug
