Repository man-group/ArcticDB, pull requests merged in 2023-05, with the labels that each got.

#253 Enhancement 119: Create, read, and drop column stats
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/column_store/column.hpp
  cpp/arcticdb/column_store/column_map.hpp
  cpp/arcticdb/column_store/memory_segment.hpp
  cpp/arcticdb/column_store/memory_segment_impl.cpp
  cpp/arcticdb/column_store/memory_segment_impl.hpp
  cpp/arcticdb/column_store/test/test_column.cpp
  cpp/arcticdb/entity/key-inl.hpp
  cpp/arcticdb/entity/key.cpp
  cpp/arcticdb/entity/type_utils.hpp
  cpp/arcticdb/pipeline/column_stats.cpp
  cpp/arcticdb/pipeline/column_stats.hpp
  cpp/arcticdb/pipeline/query.hpp
  cpp/arcticdb/pipeline/read_pipeline.hpp
  cpp/arcticdb/pipeline/value.hpp
  cpp/arcticdb/processing/aggregation.cpp
  cpp/arcticdb/processing/aggregation.hpp
  cpp/arcticdb/processing/aggregation_interface.hpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/python/python_module.cpp
  cpp/arcticdb/storage/lmdb/lmdb_storage-inl.hpp
  cpp/arcticdb/storage/python_bindings.cpp
  cpp/arcticdb/stream/segment_aggregator.hpp
  cpp/arcticdb/util/error_code.hpp
  cpp/arcticdb/util/preconditions.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/test/test_version_store.cpp
  cpp/arcticdb/version/version_core.cpp
  cpp/arcticdb/version/version_core.hpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  docs/mkdocs/docs/error_messages.md
  python/arcticdb/version_store/_store.py
  python/tests/unit/arcticdb/test_column_stats.py
Labels: enhancement

#371 Fix flaky test in newer pandas version
  python/tests/unit/arcticdb/version_store/test_aggregation.py
Labels: bug

#335 Document the hierarchy of Python exceptions.
  docs/mkdocs/docs/error_messages.md
Labels: documentation

#442 Add Azurite in Github Action's Linux testing environment
  .github/workflows/build_steps.yml
Labels: enhancement
