Repository man-group/ArcticDB, pull requests merged in 2024-03, with the labels that each got.

#1383 Refactor: Move mongo client errors handling into mongo_storage.cpp
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/storage/mongo/mongo_client.cpp
  cpp/arcticdb/storage/mongo/mongo_client.hpp
  cpp/arcticdb/storage/mongo/mongo_client_wrapper.hpp
  cpp/arcticdb/storage/mongo/mongo_storage.cpp
Labels: refactor

#1280 Not allowing snapshotting tombstoned versions
  cpp/arcticdb/version/version_map_batch_methods.hpp
  cpp/arcticdb/version/version_map_entry.hpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  python/arcticdb/util/tasks.py
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_snapshot.py
Labels: bug

#1413 pin github-script on 4.0.x release branch
  .github/workflows/publish.yml
Labels: bug

#1411 #447 Mongo Exceptions Normalization
  cpp/arcticdb/python/python_module.cpp
  cpp/arcticdb/storage/library.hpp
  cpp/arcticdb/storage/mongo/mongo_client_wrapper.hpp
  cpp/arcticdb/storage/mongo/mongo_mock_client.cpp
  cpp/arcticdb/storage/mongo/mongo_storage.cpp
  cpp/arcticdb/storage/python_bindings.cpp
  cpp/arcticdb/storage/python_bindings.hpp
  cpp/arcticdb/storage/storage_exceptions.hpp
  cpp/arcticdb/storage/test/test_storage_exceptions.cpp
  cpp/arcticdb/util/error_code.hpp
  cpp/arcticdb/version/symbol_list.cpp
  docs/mkdocs/docs/error_messages.md
  python/arcticdb/exceptions.py
Labels: enhancement

#1410 Allow different testing dependency version in pipeline
  .github/workflows/build_steps.yml
Labels: bug

#1419 read_batch set include_deleted to false by default when reading a version
  cpp/arcticdb/version/version_map_batch_methods.cpp
  python/tests/hypothesis/arcticdb/test_hypothesis_version_store.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
Labels: Bug fixing drive Q1 2024

#1437 Bug Fix Windows: Remove lmdb files when `delete_library` is called
  cpp/arcticdb/storage/library.hpp
  cpp/arcticdb/storage/library_manager.cpp
  cpp/arcticdb/storage/library_manager.hpp
  cpp/arcticdb/storage/lmdb/lmdb_storage.cpp
  cpp/arcticdb/storage/lmdb/lmdb_storage.hpp
  cpp/arcticdb/storage/python_bindings.cpp
  cpp/arcticdb/storage/storage.hpp
  cpp/arcticdb/storage/storages.hpp
  cpp/arcticdb/storage/test/test_storage_exceptions.cpp
  python/arcticdb/adapters/arctic_library_adapter.py
  python/arcticdb/adapters/lmdb_library_adapter.py
  python/arcticdb/adapters/prefixing_library_adapter_decorator.py
  python/arcticdb/arctic.py
  python/tests/integration/arcticdb/test_lmdb.py
Labels: bug
