Repository man-group/ArcticDB, pull requests merged in 2024-01, with the labels that each got.

#1181 Sorting speed improvements in SegmentInMemory
  cpp/arcticdb/column_store/column.cpp
  cpp/arcticdb/column_store/column.hpp
  cpp/arcticdb/column_store/memory_segment_impl.cpp
Labels: enhancement

#1203 Docs that StorageFailureSimulator is not used in all stores
  cpp/arcticdb/storage/failure_simulation.hpp
Labels: documentation

#1199 build: Adapt protobuf compilation
  .github/workflows/build_with_conda.yml
  python/arcticc/pb2/__init__.py
  setup.py
Labels: bug

#1215 Enable skipped test_partial_write_hashed
  python/tests/unit/arcticdb/version_store/test_engine.py
Labels: bug

#1244 conda-build: Explicitly depend on openssl and libcurl
  environment_unix.yml
Labels: bug

#1272 Reintroduce attrs as a runtime dependency
  environment_unix.yml
  setup.cfg
Labels: bug

#1276 Bugfix 902: Cannot filter on nans and nones
  cpp/arcticdb/entity/types.hpp
  cpp/arcticdb/processing/operation_dispatch_unary.cpp
  cpp/arcticdb/processing/operation_dispatch_unary.hpp
  cpp/arcticdb/processing/operation_types.hpp
  cpp/arcticdb/util/constants.hpp
  cpp/arcticdb/util/offset_string.hpp
  cpp/arcticdb/util/sparse_utils.hpp
  cpp/arcticdb/version/python_bindings.cpp
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_filtering.py
  python/tests/unit/arcticdb/version_store/test_filtering_dynamic.py
Labels: enhancement
