Repository man-group/ArcticDB, pull requests merged in 2024-04, with the labels that each got.

#1473 Fix SYMBOL_LIST Segment index out of bounds bug
  cpp/arcticdb/column_store/memory_segment_impl.cpp
  cpp/arcticdb/version/symbol_list.cpp
Labels: bug

#1467 Bugfix/1250/compact incompletes rationalisation
  cpp/arcticdb/column_store/column.cpp
  cpp/arcticdb/column_store/memory_segment_impl.cpp
  cpp/arcticdb/stream/merge_utils.hpp
  cpp/arcticdb/stream/segment_aggregator.hpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/test/test_version_store.cpp
  cpp/arcticdb/version/version_core.cpp
  python/tests/stress/arcticdb/version_store/test_stress_append.py
  python/tests/unit/arcticdb/version_store/test_parallel.py
Labels: bug

#1482 Restore mistake in #1315
  cpp/arcticdb/storage/azure/azure_storage.cpp
  python/tests/integration/arcticdb/test_arctic_batch.py
Labels: bug

#1338 Add s3 custom ca support
  cpp/arcticdb/storage/python_bindings.cpp
  cpp/arcticdb/storage/s3/s3_storage.hpp
  cpp/arcticdb/storage/storage_override.hpp
  cpp/proto/arcticc/pb2/nfs_backed_storage.proto
  cpp/proto/arcticc/pb2/s3_storage.proto
  environment_unix.yml
  python/arcticdb/adapters/s3_library_adapter.py
  python/arcticdb/storage_fixtures/s3.py
  python/arcticdb/storage_fixtures/utils.py
  python/arcticdb/version_store/helper.py
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/storage_fixtures/test_s3.py
  python/tests/util/mark.py
  setup.cfg
Labels: enhancement

#1483 Consistently handle timezones in `QueryBuilder` filtering
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_query_builder.py
Labels: bug

#1487 Align azure timeout with s3
  cpp/arcticdb/storage/azure/azure_storage.cpp
Labels: bug

#1481 bugfix/1247: Don't create an lmdb library if the name is invalid.
  cpp/arcticdb/async/async_store.hpp
  cpp/arcticdb/storage/library.hpp
  cpp/arcticdb/storage/library_manager.cpp
  cpp/arcticdb/storage/lmdb/lmdb_storage.cpp
  cpp/arcticdb/storage/lmdb/lmdb_storage.hpp
  cpp/arcticdb/storage/storage.hpp
  cpp/arcticdb/storage/storages.hpp
  cpp/arcticdb/storage/test/in_memory_store.hpp
  cpp/arcticdb/stream/stream_sink.hpp
  cpp/arcticdb/util/name_validation.cpp
  cpp/arcticdb/util/name_validation.hpp
  python/tests/integration/arcticdb/test_lmdb.py
Labels: bug

#1503 bugfix/1247:address comments in #1481
  cpp/arcticdb/storage/lmdb/lmdb_storage.cpp
  cpp/arcticdb/util/name_validation.cpp
  python/tests/integration/arcticdb/test_lmdb.py
Labels: refactor

#1513 Support mongodb+srv connection strings
  python/arcticdb/adapters/mongo_library_adapter.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: enhancement

#1522 Cleanup arctic client after usage in local_quary_builder in ASV
  python/benchmarks/local_query_builder.py
Labels: bug

#1523 Bugfix/1518/get description date range incorrect after delete data in range
  cpp/arcticdb/entity/descriptor_item.hpp
  cpp/arcticdb/pipeline/write_frame.cpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/python_bindings.cpp
  python/tests/integration/arcticdb/test_arctic_batch.py
  python/tests/integration/arcticdb/version_store/test_deletion.py
Labels: bug

#1529 Bugfix 1507+1509: dynamic schema different index append fixes
  cpp/arcticdb/python/normalization_checks.cpp
  cpp/arcticdb/version/schema_checks.hpp
  python/tests/unit/arcticdb/version_store/test_append.py
  python/tests/unit/arcticdb/version_store/test_empty_column_type.py
  python/tests/unit/arcticdb/version_store/test_filtering_dynamic.py
Labels: bug

#1531 list_snapshots: Add option to skip loading metadata
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: enhancement

#1533 LibraryTool add read_index
  python/arcticdb/toolbox/library_tool.py
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: enhancement
