Repository man-group/ArcticDB, pull requests merged in 2024-09, with the labels that each got.

#1794 Enhancement 1792: Use float64 as the result type for all division operations in the processing pipeline
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/operation_types.hpp
  cpp/arcticdb/processing/test/test_arithmetic_type_promotion.cpp
  python/arcticdb/util/hypothesis.py
  python/tests/unit/arcticdb/version_store/test_projection_hypothesis.py
Labels: enhancement, api break

#1747 Always use strict weak ordering in std::sort comparators
  cpp/arcticdb/processing/clause.cpp
Labels: bug

#1745 Use EncodedFieldImpl.blocks() rather than casting member variable _blocks
  cpp/arcticdb/codec/encoded_field.hpp
Labels: bug

#1764 Improve full build time by 30% by adding PCH
  cpp/CMakeLists.txt
  cpp/CMakePresets.json
  cpp/arcticdb/CMakeLists.txt
Labels: enhancement

#1703 Enhancement 1750: lazy dataframe implementation
  python/arcticdb/__init__.py
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_lazy_dataframe.py
  python/tests/unit/arcticdb/version_store/test_query_builder.py
Labels: enhancement

#1821 Bugfix 1818: Fix QueryBuilder equality checks (#1819)
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_query_builder.py
Labels: bug
