Repository man-group/ArcticDB, pull requests merged in 2024-02, with the labels that each got.

#1301 Refactor 1278: Column data dense forward iterator
  cpp/arcticdb/column_store/column.hpp
  cpp/arcticdb/column_store/column_data.hpp
  cpp/arcticdb/column_store/segment_utils.hpp
  cpp/arcticdb/entity/types.hpp
  cpp/arcticdb/processing/aggregation.cpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/expression_node.hpp
  cpp/arcticdb/processing/operation_dispatch.cpp
  cpp/arcticdb/processing/operation_dispatch_binary.cpp
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/operation_dispatch_unary.cpp
  cpp/arcticdb/processing/operation_dispatch_unary.hpp
  cpp/arcticdb/processing/test/test_operation_dispatch.cpp
Labels: refactor

#1309 Add __contains__ to Arctic class, to support lib in arctic
  python/arcticdb/arctic.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: bug

#1282 Update BSL table for v4.3.0
  README.md
Labels: documentation

#1243 Align docstring with the behaviour
  python/arcticdb/version_store/_store.py
Labels: bug

#1319 Added 142 new tests for empty/missing operations
  python/tests/unit/arcticdb/version_store/test_missing_empty.py
Labels: bug

#1315 Abstract AzureClientWrapper out of azure_storage.cpp
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/storage/azure/azure_client_wrapper.hpp
  cpp/arcticdb/storage/azure/azure_real_client.cpp
  cpp/arcticdb/storage/azure/azure_real_client.hpp
  cpp/arcticdb/storage/azure/azure_storage.cpp
  cpp/arcticdb/storage/azure/azure_storage.hpp
Labels: refactor

#1290 Minor improvement on analysis flow
  .github/workflows/analysis_workflow.yml
Labels: enhancement

#1347 Use type-deduced functor for all column iterating functions
  cpp/arcticdb/column_store/column.hpp
Labels: enhancement

#1344 #447 Azure Storage Exceptions Normalization
  cpp/arcticdb/storage/azure/azure_client_wrapper.hpp
  cpp/arcticdb/storage/azure/azure_mock_client.cpp
  cpp/arcticdb/storage/azure/azure_mock_client.hpp
  cpp/arcticdb/storage/azure/azure_storage.cpp
  cpp/arcticdb/storage/s3/s3_mock_client.cpp
  cpp/arcticdb/storage/test/common.hpp
  cpp/arcticdb/storage/test/test_azure_storage.cpp
  cpp/arcticdb/storage/test/test_storage_exceptions.cpp
  cpp/arcticdb/util/error_code.hpp
  docs/mkdocs/docs/error_messages.md
Labels: enhancement
