Repository man-group/ArcticDB, pull requests merged in 2024-08, with the labels that each got.

#1732 Fix use after move in `op_log.cpp`
  cpp/arcticdb/version/op_log.cpp
Labels: bug

#1741 Refactor/1722/remove composite from processing pipeline
  cpp/arcticdb/async/tasks.hpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/processing/component_manager.hpp
  cpp/arcticdb/processing/processing_unit.cpp
  cpp/arcticdb/processing/processing_unit.hpp
  cpp/arcticdb/processing/test/benchmark_clause.cpp
  cpp/arcticdb/processing/test/test_clause.cpp
  cpp/arcticdb/processing/test/test_resample.cpp
  cpp/arcticdb/version/version_core.cpp
  python/tests/unit/arcticdb/version_store/test_aggregation.py
  python/tests/unit/arcticdb/version_store/test_aggregation_dynamic.py
  python/tests/unit/arcticdb/version_store/test_query_builder_sparse.py
Labels: refactor

#1763 Fixes for sort and finalize
  cpp/arcticdb/pipeline/frame_slice.hpp
  cpp/arcticdb/pipeline/frame_utils.cpp
  cpp/arcticdb/pipeline/index_utils.hpp
  cpp/arcticdb/pipeline/read_pipeline.hpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/stream/append_map.cpp
  cpp/arcticdb/stream/merge.hpp
  cpp/arcticdb/util/error_code.hpp
  cpp/arcticdb/version/version_core-inl.hpp
  cpp/arcticdb/version/version_core.cpp
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/unit/arcticdb/version_store/test_sort_merge.py
Labels: bug

#1664 Bugfix 1552: Set row_count/rows to None in get_description/get_info and batch versions thereof if symbol is pickled
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_api.py
Labels: bug, api break

#1642 Bugfix 1641: Remove unused staged arg from write_pickle_batch
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic_batch.py
Labels: bug, api break

#1758 Refactor 1749: make processing tests great again
  cpp/arcticdb/column_store/column_map.hpp
  cpp/arcticdb/column_store/memory_segment_impl.cpp
  cpp/arcticdb/pipeline/filter_segment.hpp
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/operation_types.hpp
  cpp/arcticdb/processing/processing_unit.cpp
  cpp/arcticdb/processing/signed_unsigned_comparison.hpp
  cpp/arcticdb/processing/test/test_arithmetic_type_promotion.cpp
  cpp/arcticdb/processing/unsorted_aggregation.cpp
  cpp/arcticdb/version/version_core.cpp
  python/arcticdb/util/hypothesis.py
  python/arcticdb/util/test.py
  python/tests/unit/arcticdb/test_column_stats.py
  python/tests/unit/arcticdb/version_store/test_aggregation.py
  python/tests/unit/arcticdb/version_store/test_aggregation_dynamic.py
  python/tests/unit/arcticdb/version_store/test_aggregation_hypothesis.py
  python/tests/unit/arcticdb/version_store/test_filtering.py
  python/tests/unit/arcticdb/version_store/test_filtering_dynamic.py
  python/tests/unit/arcticdb/version_store/test_filtering_hypothesis.py
  python/tests/unit/arcticdb/version_store/test_projection.py
  python/tests/unit/arcticdb/version_store/test_projection_dynamic.py
  python/tests/unit/arcticdb/version_store/test_projection_hypothesis.py
  python/tests/unit/arcticdb/version_store/test_query_builder.py
  python/tests/unit/arcticdb/version_store/test_query_builder_batch.py
  python/tests/unit/arcticdb/version_store/test_query_builder_sparse.py
  python/tests/unit/arcticdb/version_store/test_resample.py
  python/tests/unit/arcticdb/version_store/test_row_range.py
Labels: bug, flaky test

#1461 Bugfix 1460: preserve nanoseconds and timezones in date range from get info
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/test_arctic_batch.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
Labels: enhancement, api break

#1672 Enhancement 1666: Do not fallback to iterating snapshots if if version as_of int or timestamp not found in version chain in V2 API
  cpp/arcticdb/pipeline/query.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/test/test_stream_version_data.cpp
  cpp/arcticdb/version/test/test_version_map_batch.cpp
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/test_arctic_batch.py
Labels: enhancement, api break
