Repository man-group/ArcticDB, pull requests merged in 2025-05, with the labels that each got.

#2304 Query Stat framework v3
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/async/test/test_async.cpp
  cpp/arcticdb/storage/s3/detail-inl.hpp
  cpp/arcticdb/toolbox/python_bindings.cpp
  cpp/arcticdb/toolbox/query_stats.cpp
  cpp/arcticdb/toolbox/query_stats.hpp
  python/arcticdb/toolbox/query_stats.py
  python/tests/conftest.py
  python/tests/integration/toolbox/test_query_stats.py
Labels: minor

#2347 Fix permissions for the automatic docs building
  .github/workflows/build_docs_on_release.yml
Labels: patch

#2344 Delete STS roles regularly
  .github/actions/set_persistent_storage_env_vars/action.yml
  .github/workflows/delete_sts_roles.yml
  python/arcticdb/storage_fixtures/s3.py
  python/utils/s3_roles_delete.py
  python/utils/test.py
Labels: patch

#2337 Disable s3 checksumming
  cpp/arcticdb/storage/s3/nfs_backed_storage.cpp
  cpp/arcticdb/storage/s3/s3_storage.cpp
  cpp/arcticdb/storage/s3/s3_storage.hpp
  cpp/arcticdb/storage/s3/s3_storage_tool.cpp
  cpp/arcticdb/storage/test/test_s3_storage.cpp
  python/arcticdb/__init__.py
  python/arcticdb/storage_fixtures/s3.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/util/mark.py
Labels: minor

#2354 Installation Tests Workflow Fixes
  .github/workflows/installation_tests.yml
Labels: patch

#2353 Patch for Real S3 library names
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_arctic_library_management.py
Labels: patch

#2350 nfs backed tests for v1 API
  python/tests/conftest.py
Labels: patch

#2351 Bugfix/9123099670/fix resampling of old updated data
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/processing/clause_utils.hpp
  cpp/arcticdb/processing/sorted_aggregation.cpp
  cpp/arcticdb/processing/test/rapidcheck_resample.cpp
  cpp/arcticdb/processing/test/test_resample.cpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/version_core.cpp
  python/arcticdb/util/venv.py
  python/tests/compat/arcticdb/test_compatibility.py
  python/tests/nonreg/arcticdb/version_store/test_nonreg_specific.py
  python/tests/unit/arcticdb/version_store/test_resample.py
Labels: bug, patch

#2362 Update installation_tests.yml with 5.3 and 5.4 final versions
  .github/workflows/installation_tests.yml
  python/installation_tests/client_utils.py
  python/installation_tests/test_installation.py
  python/tests/compat/requirements-5.3.4.txt
  python/tests/compat/requirements-5.3.4.yml
  python/tests/compat/requirements-5.4.1.txt
  python/tests/compat/requirements-5.4.1.yml
Labels: patch

#2363 Fix multiindex series
  cpp/arcticdb/pipeline/frame_slice_map.hpp
  python/tests/unit/arcticdb/version_store/test_normalization.py
Labels: bug, patch

#2349 Fix gcp lib unreachable after making it read only
  .github/actions/set_persistent_storage_env_vars/action.yml
  cpp/arcticdb/storage/s3/s3_settings.hpp
  python/arcticdb/version_store/_store.py
  python/tests/integration/arcticdb/version_store/test_symbol_list.py
Labels: patch

#2309 Query Stats s3 v3
  cpp/arcticdb/async/test/test_async.cpp
  cpp/arcticdb/storage/s3/detail-inl.hpp
  cpp/arcticdb/toolbox/python_bindings.cpp
  cpp/arcticdb/toolbox/query_stats.cpp
  cpp/arcticdb/toolbox/query_stats.hpp
  docs/mkdocs/docs/api/query_stats.md
  docs/mkdocs/docs/tutorials/query_stats.md
  docs/mkdocs/mkdocs.yml
  python/arcticdb/toolbox/query_stats.py
  python/tests/integration/toolbox/test_query_stats.py
Labels: minor

#2371 Fix for scheduled workflow build failures to appear in slack
  .github/workflows/failure_notification.yaml
Labels: patch

#2374 Fix automatic docs build
  .github/workflows/build_docs_on_release.yml
Labels: patch, no-release-notes

#2373 New versions 5.5 and 5.6 added to installation tests monitoring
  .github/workflows/installation_tests.yml
  python/tests/compat/requirements-5.2.4.txt
  python/tests/compat/requirements-5.2.4.yml
  python/tests/compat/requirements-5.2.6.txt
  python/tests/compat/requirements-5.5.1.txt
  python/tests/compat/requirements-5.5.1.yml
  python/tests/compat/requirements-5.6.0.txt
  python/tests/compat/requirements-5.6.0.yml
Labels: patch

#2352 Implement delete versions funcationality
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/test/test_version_map.cpp
  cpp/arcticdb/version/version_functions.hpp
  cpp/arcticdb/version/version_map.hpp
  cpp/arcticdb/version/version_map_entry.hpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  cpp/arcticdb/version/version_store_objects.hpp
  python/.asv/results/benchmarks.json
  python/arcticdb/util/tasks.py
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/benchmarks/basic_functions.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_dedup.py
  python/tests/integration/arcticdb/version_store/test_deletion.py
  python/tests/integration/arcticdb/version_store/test_symbol_list.py
  python/tests/integration/toolbox/test_library_tool.py
  python/tests/integration/toolbox/test_storage_mover.py
  python/tests/stress/arcticdb/version_store/test_stress_version_map_compact.py
  python/tests/unit/arcticdb/test_column_stats.py
  python/tests/unit/arcticdb/version_store/test_deletion.py
Labels: enhancement, minor

#2376 Respect legacy env vars
  python/arcticdb/tools.py
  python/tests/unit/arcticdb/test_env_vars.py
Labels: bug, patch
