Repository man-group/ArcticDB, pull requests merged in 2025-08, with the labels that each got.

#2539 Repro for pandas normalization failures
  python/tests/unit/arcticdb/version_store/test_normalization.py
Labels: patch, no-release-notes

#2538 Faster and error free ASV benchmarks
  .github/workflows/benchmark_commits.yml
  .github/workflows/build_steps.yml
  .github/workflows/build_with_conda.yml
  .github/workflows/installation_tests.yml
  build_tooling/parallel_test.sh
  python/.asv/results/benchmarks.json
  python/benchmarks/basic_functions.py
  python/benchmarks/bi_benchmarks.py
  python/benchmarks/comparison_benchmarks.py
  python/benchmarks/finalize_staged_data.py
  python/benchmarks/list_functions.py
  python/benchmarks/list_snapshots.py
  python/benchmarks/local_query_builder.py
  python/benchmarks/persistent_query_builder.py
  python/benchmarks/resample.py
  python/benchmarks/version_chain.py
Labels: patch

#2511 Fix installation tests
  .github/actions/set_persistent_storage_env_vars/action.yml
  .github/workflows/build_steps.yml
  .github/workflows/installation_tests.yml
  python/installation_tests/test_installation.py
  python/tests/compat/requirements-5.9.3.txt
  python/tests/compat/requirements-5.9.3.yml
Labels: patch

#2540 Fix performance regression
  cpp/arcticdb/processing/clause.cpp
Labels: patch, no-release-notes

#2541 One line change to make getting library tool for Native Mongoose libraries easier
  python/arcticdb/version_store/_store.py
Labels: patch

#2542 Upgrade compiler used for coverity runs
  .github/workflows/static_analysis.yml
Labels: patch, no-release-notes

#2545 Fix man.arcticdb tests
  python/tests/unit/arcticdb/version_store/test_arrow.py
Labels: patch, no-release-notes

#2534 Fix get_backing_store could check non-primary storage
  python/arcticdb/version_store/_store.py
  python/tests/integration/arcticdb/test_arctic.py
Labels: minor

#2549 Fix installation tests
  .github/workflows/installation_tests.yml
Labels: patch

#2552 Update compat deps
  build_tooling/requirements-compatibility-py311.txt
  build_tooling/requirements-compatibility-py38.txt
Labels: patch, no-release-notes

#2547 Bugfix 9685477375: Use std::allocator everywhere sparrow might be involved
  cpp/arcticdb/column_store/block.hpp
  cpp/arcticdb/column_store/chunked_buffer.hpp
  cpp/arcticdb/pipeline/pipeline_utils.hpp
  cpp/arcticdb/python/numpy_buffer_holder.hpp
  cpp/arcticdb/util/allocator.cpp
  cpp/arcticdb/util/allocator.hpp
  python/tests/unit/arcticdb/version_store/test_arrow.py
Labels: patch, no-release-notes

#2553 Fix release build on GCC 13.3
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/storage/coalesced/multi_segment_utils.hpp
  cpp/arcticdb/util/allocator.cpp
Labels: patch, no-release-notes

#2554 Remove xfailed tests for projection and filtering on an empty dataframe
  python/tests/unit/arcticdb/version_store/test_filtering.py
  python/tests/unit/arcticdb/version_store/test_projection.py
Labels: patch, no-release-notes

#2550 Support open ended row_range on QueryBuilder and read methods
  cpp/arcticdb/column_store/memory_segment_impl.hpp
  cpp/arcticdb/pipeline/read_query.cpp
  cpp/arcticdb/pipeline/read_query.hpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/version/python_bindings.cpp
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_row_range.py
Labels: minor

#2497 Storage lock increase wait time and add artificial slow writes
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/python/python_module.cpp
  cpp/arcticdb/storage/failure_simulation.cpp
  cpp/arcticdb/storage/failure_simulation.hpp
  cpp/arcticdb/util/configs_map.cpp
  cpp/arcticdb/util/configs_map.hpp
  cpp/arcticdb/util/storage_lock.hpp
  cpp/arcticdb/util/test/test_storage_lock.cpp
  cpp/proto/arcticc/pb2/storage.proto
  python/tests/integration/toolbox/test_query_stats.py
  python/tests/stress/arcticdb/version_store/test_stress_symbol_list_cache.py
Labels: patch

#2544 Remove signaled threads on TaskScheduler destruction on Windows
  cpp/arcticdb/async/task_scheduler.cpp
  cpp/arcticdb/async/task_scheduler.hpp
  cpp/arcticdb/util/global_lifetimes.cpp
  python/tests/stress/arcticdb/version_store/test_deallocation.py
Labels: patch

#2407 Add utilities to let the storage failure simulator simulate high latency conditions
  cpp/arcticdb/storage/failure_simulation.hpp
  cpp/arcticdb/storage/test/in_memory_store.hpp
  cpp/arcticdb/util/key_utils.hpp
  cpp/arcticdb/version/version_store_api.hpp
Labels: patch

#2558 Mem leaks - increase mem limits so that we have time to create ASV tests
  python/tests/stress/arcticdb/version_store/test_mem_leaks.py
Labels: patch

#2555 Use worksteal for pytest
  .github/workflows/build.yml
  .github/workflows/build_with_conda.yml
Labels: patch, no-release-notes

#2515 Utility for writing segment_in_memory
  cpp/arcticdb/column_store/memory_segment_impl.cpp
  cpp/arcticdb/pipeline/slicing.hpp
  cpp/arcticdb/toolbox/library_tool.cpp
  cpp/arcticdb/toolbox/library_tool.hpp
  cpp/arcticdb/toolbox/python_bindings.cpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/test/test_sparse.cpp
  cpp/arcticdb/version/version_core.cpp
  cpp/arcticdb/version/version_core.hpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  cpp/arcticdb/version/versioned_engine.hpp
  python/arcticdb/toolbox/library_tool.py
  python/tests/integration/toolbox/test_library_tool.py
Labels: enhancement, patch

#2572 Disable operation on objects of mismatched types leading to corruption [Bugfix 9754433454]
  cpp/arcticdb/entity/types_proto.hpp
  cpp/arcticdb/python/normalization_checks.cpp
  cpp/arcticdb/version/schema_checks.cpp
  python/tests/unit/arcticdb/version_store/test_append.py
  python/tests/unit/arcticdb/version_store/test_update.py
Labels: patch

#2578 Fix ASV test failures and Installation Test Failures on Master
  .github/actions/set_persistent_storage_env_vars/action.yml
  .github/workflows/build_with_conda.yml
  python/arcticdb/storage_fixtures/azure.py
  python/installation_tests/client_utils.py
  python/installation_tests/mark.py
  python/installation_tests/test_installation.py
Labels: patch

#2580 Fix entire column default initialize for arrow
  cpp/arcticdb/column_store/chunked_buffer.hpp
  cpp/arcticdb/column_store/column.cpp
  cpp/arcticdb/pipeline/read_frame.cpp
  cpp/arcticdb/util/cursored_buffer.hpp
  python/tests/unit/arcticdb/version_store/test_arrow.py
Labels: patch, no-release-notes

#2557 Fix test_type_promotion_int64_and_float64_up_to_float64
  python/tests/unit/arcticdb/version_store/test_column_type_changes.py
Labels: patch

#2586 Arrow fix string cols with nones and nans
  cpp/arcticdb/arrow/arrow_handlers.cpp
  cpp/arcticdb/pipeline/column_mapping.hpp
  cpp/arcticdb/pipeline/read_frame.cpp
  python/tests/unit/arcticdb/version_store/test_arrow.py
Labels: patch, no-release-notes

#2591 Move implementations from .hpp to .cpp for the most expensive headers [9837818212]
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/arrow/arrow_handlers.cpp
  cpp/arcticdb/codec/segment_header.cpp
  cpp/arcticdb/column_store/column.cpp
  cpp/arcticdb/column_store/column.hpp
  cpp/arcticdb/column_store/key_segment.cpp
  cpp/arcticdb/column_store/memory_segment.cpp
  cpp/arcticdb/column_store/memory_segment.hpp
  cpp/arcticdb/column_store/memory_segment_impl.cpp
  cpp/arcticdb/column_store/memory_segment_impl.hpp
  cpp/arcticdb/pipeline/pipeline_context.cpp
  cpp/arcticdb/processing/component_manager.hpp
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/sorted_aggregation.hpp
  cpp/arcticdb/python/reader.hpp
  cpp/arcticdb/storage/coalesced/multi_segment_utils.hpp
Labels: patch, no-release-notes

#2592 GCP installation tests fail on first versions when GCP was introduced
  .github/workflows/installation_tests.yml
  python/installation_tests/conftest.py
Labels: patch

#2583 Resilient start of simulated storages
  python/arcticdb/storage_fixtures/azure.py
  python/arcticdb/storage_fixtures/mongo.py
  python/arcticdb/storage_fixtures/utils.py
Labels: patch

#2593 Added new test utilities
  cpp/arcticdb/util/test/generators.hpp
  python/tests/integration/toolbox/test_library_tool.py
Labels: enhancement, patch

#2601 Fix flaky resampling hypothesis tests caused by a bug in Pandas when origin is end_day and closed is right [9826689202]
  python/arcticdb/util/test.py
Labels: patch, no-release-notes

#2548 Add docstring and warning for disparity between `will_item_be_pickled` and `is_symbol_pickle`
  docs/mkdocs/docs/runtime_config.md
  python/arcticdb/log.py
  python/arcticdb/version_store/_store.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
Labels: minor

#2603 delete_container() operation for Azurite should not be reason tests to fail
  python/arcticdb/storage_fixtures/azure.py
Labels: patch

#2590 asv flakiness fixes
  python/.asv/results/benchmarks.json
  python/benchmarks/arrow.py
  python/benchmarks/basic_functions.py
  python/benchmarks/bi_benchmarks.py
  python/benchmarks/comparison_benchmarks.py
  python/benchmarks/finalize_staged_data.py
  python/benchmarks/list_functions.py
  python/benchmarks/list_snapshots.py
  python/benchmarks/local_query_builder.py
  python/benchmarks/persistent_query_builder.py
  python/benchmarks/resample.py
  python/benchmarks/version_chain.py
Labels: patch

#2621 xfail for now noisy test
  python/tests/stress/arcticdb/version_store/test_deallocation.py
Labels: patch
