Repository man-group/ArcticDB, pull requests merged in 2025-07, with the labels that each got.

#2438 Pin numpy as on older manylinux we use it can't compile
  setup.cfg
Labels: patch

#2445 Update BSL table with missing releases
  README.md
Labels: patch

#2387 Rework C++ truncation for arrow
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/arrow/arrow_utils.cpp
  cpp/arcticdb/column_store/block.hpp
  cpp/arcticdb/column_store/chunked_buffer.hpp
  cpp/arcticdb/column_store/column.cpp
  cpp/arcticdb/column_store/column.hpp
  cpp/arcticdb/column_store/memory_segment.hpp
  cpp/arcticdb/column_store/memory_segment_impl.hpp
  cpp/arcticdb/column_store/test/benchmark_column.cpp
  cpp/arcticdb/column_store/test/rapidcheck_chunked_buffer.cpp
  cpp/arcticdb/entity/index_range.hpp
  cpp/arcticdb/pipeline/frame_slice.hpp
  cpp/arcticdb/pipeline/query.cpp
  cpp/arcticdb/pipeline/query.hpp
  cpp/arcticdb/pipeline/read_frame.cpp
  cpp/arcticdb/pipeline/read_query.hpp
  cpp/arcticdb/pipeline/write_frame.cpp
  cpp/arcticdb/processing/test/benchmark_ternary.cpp
  cpp/arcticdb/util/magic_num.hpp
  cpp/arcticdb/version/version_core.cpp
  python/arcticdb/version_store/_store.py
  python/tests/compat/arcticdb/test_compatibility.py
  python/tests/conftest.py
  python/tests/integration/arcticdb/test_s3.py
  python/tests/integration/arcticdb/version_store/test_num_storage_operations.py
  python/tests/unit/arcticdb/version_store/test_arrow.py
Labels: patch

#2449 Xfail segmentation fault tests
  .github/workflows/build_steps.yml
  .github/workflows/build_with_conda.yml
  python/tests/unit/arcticdb/version_store/test_symbol_concatenation.py
Labels: patch

#2453 Manually install openssl in MacOS CI build
  .github/workflows/build_steps.yml
Labels: patch, no-release-notes

#2447 Remove pin on sparrow
  environment-dev.yml
Labels: patch

#2385 Query Builder regex filter support and upgrade PCRE to PCRE2
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/column_store/string_pool.cpp
  cpp/arcticdb/column_store/string_pool.hpp
  cpp/arcticdb/processing/expression_context.hpp
  cpp/arcticdb/processing/expression_node.hpp
  cpp/arcticdb/processing/operation_dispatch_binary.cpp
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/operation_types.hpp
  cpp/arcticdb/processing/processing_unit.cpp
  cpp/arcticdb/processing/test/benchmark_binary.cpp
  cpp/arcticdb/processing/test/benchmark_common.cpp
  cpp/arcticdb/processing/test/benchmark_common.hpp
  cpp/arcticdb/processing/test/benchmark_ternary.cpp
  cpp/arcticdb/python/python_module.cpp
  cpp/arcticdb/stream/stream_utils.hpp
  cpp/arcticdb/util/python_bindings.cpp
  cpp/arcticdb/util/python_bindings.hpp
  cpp/arcticdb/util/regex_filter.hpp
  cpp/arcticdb/util/test/test_regex.cpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/vcpkg.json
  environment-dev.yml
  python/.asv/results/benchmarks.json
  python/arcticdb/version_store/processing.py
  python/benchmarks/local_query_builder.py
  python/tests/unit/arcticdb/version_store/test_filtering.py
  python/tests/unit/arcticdb/version_store/test_lazy_dataframe.py
Labels: minor

#2419 Staged data new API
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/entity/stage_result.hpp
  cpp/arcticdb/stream/incompletes.cpp
  cpp/arcticdb/stream/incompletes.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  cpp/arcticdb/version/versioned_engine.hpp
  python/arcticdb/version_store/_store.py
  python/arcticdb/version_store/library.py
  python/tests/unit/arcticdb/version_store/test_api.py
  python/tests/unit/arcticdb/version_store/test_pickle_atomkey.py
  python/tests/unit/arcticdb/version_store/test_sort.py
  python/tests/unit/arcticdb/version_store/test_stage.py
Labels: patch, no-release-notes

#2465 Revert "Query Builder regex filter support and upgrade PCRE to PCRE2…(#2385)"
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/column_store/string_pool.cpp
  cpp/arcticdb/column_store/string_pool.hpp
  cpp/arcticdb/processing/expression_context.hpp
  cpp/arcticdb/processing/expression_node.hpp
  cpp/arcticdb/processing/operation_dispatch_binary.cpp
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/operation_types.hpp
  cpp/arcticdb/processing/processing_unit.cpp
  cpp/arcticdb/processing/test/benchmark_binary.cpp
  cpp/arcticdb/processing/test/benchmark_common.cpp
  cpp/arcticdb/processing/test/benchmark_common.hpp
  cpp/arcticdb/processing/test/benchmark_ternary.cpp
  cpp/arcticdb/python/python_module.cpp
  cpp/arcticdb/stream/stream_utils.hpp
  cpp/arcticdb/util/python_bindings.cpp
  cpp/arcticdb/util/python_bindings.hpp
  cpp/arcticdb/util/regex_filter.hpp
  cpp/arcticdb/util/test/test_regex.cpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/vcpkg.json
  environment-dev.yml
  python/.asv/results/benchmarks.json
  python/arcticdb/version_store/processing.py
  python/benchmarks/local_query_builder.py
  python/tests/unit/arcticdb/version_store/test_filtering.py
  python/tests/unit/arcticdb/version_store/test_lazy_dataframe.py
Labels: minor

#2473 Use a less strict pin for sparrow
  environment-dev.yml
Labels: patch

#2466 Query Builder regex filter support and upgrade PCRE to PCRE2 V2
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/column_store/string_pool.cpp
  cpp/arcticdb/column_store/string_pool.hpp
  cpp/arcticdb/processing/expression_context.hpp
  cpp/arcticdb/processing/expression_node.hpp
  cpp/arcticdb/processing/operation_dispatch_binary.cpp
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/operation_types.hpp
  cpp/arcticdb/processing/processing_unit.cpp
  cpp/arcticdb/processing/test/benchmark_binary.cpp
  cpp/arcticdb/processing/test/benchmark_common.cpp
  cpp/arcticdb/processing/test/benchmark_common.hpp
  cpp/arcticdb/processing/test/benchmark_ternary.cpp
  cpp/arcticdb/python/python_module.cpp
  cpp/arcticdb/stream/stream_utils.hpp
  cpp/arcticdb/util/python_bindings.cpp
  cpp/arcticdb/util/python_bindings.hpp
  cpp/arcticdb/util/regex_filter.hpp
  cpp/arcticdb/util/test/test_regex.cpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/vcpkg.json
  environment-dev.yml
  python/.asv/results/benchmarks.json
  python/arcticdb/version_store/processing.py
  python/benchmarks/local_query_builder.py
  python/tests/unit/arcticdb/version_store/test_filtering.py
  python/tests/unit/arcticdb/version_store/test_lazy_dataframe.py
Labels: minor

#2448 Extend testing for the index names returned by get_info
  cpp/arcticdb/stream/python_bindings.cpp
  python/arcticdb/version_store/_normalization.py
  python/arcticdb/version_store/_store.py
  python/tests/compat/arcticdb/test_compatibility.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
  python/tests/unit/arcticdb/version_store/test_unicode.py
Labels: patch

#2458 Fix flaky segfault in concat testing
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  python/tests/unit/arcticdb/version_store/test_symbol_concatenation.py
Labels: patch

#2479 maint: Replace Folly's ranges with the standard library's
  cpp/arcticdb/entity/test/test_atom_key.cpp
  cpp/arcticdb/entity/variant_key.hpp
  cpp/arcticdb/storage/common.hpp
  cpp/arcticdb/storage/library.hpp
  cpp/arcticdb/storage/library_manager.cpp
  cpp/arcticdb/storage/library_path.hpp
  cpp/arcticdb/storage/mongo/mongo_storage.hpp
  cpp/arcticdb/storage/s3/detail-inl.hpp
  cpp/arcticdb/storage/test/test_storage_factory.cpp
  cpp/arcticdb/stream/index.cpp
  cpp/arcticdb/stream/python_bindings.cpp
  cpp/arcticdb/stream/row_builder.hpp
  cpp/arcticdb/stream/stream_reader.hpp
  cpp/arcticdb/stream/stream_utils.hpp
  cpp/arcticdb/stream/test/stream_test_common.hpp
  cpp/arcticdb/util/composite.hpp
  cpp/arcticdb/version/version_map.hpp
Labels: patch

#2482 conda-build: Use macos-14
  .github/workflows/build_with_conda.yml
Labels: patch

#2496 Move PCRE2_CODE_UNIT_WIDTH to CMake
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/util/regex_filter.hpp
Labels: patch, no-release-notes

#2508 Remove matrix from macos flow as it is not needed
  .github/workflows/build_with_conda.yml
Labels: patch, no-release-notes

#2507 Make append_batch and update_batch noop with empty dataframes when there's an existing version
  cpp/arcticdb/version/local_versioned_engine.cpp
  python/tests/integration/arcticdb/test_arctic_batch.py
  python/tests/integration/arcticdb/test_update.py
  python/tests/unit/arcticdb/version_store/test_update.py
Labels: patch

#2516 Ignore errors when trying to delete the mac wheels
  .github/workflows/publish.yml
Labels: patch, no-release-notes

#2486 Release the GIL when logging from the Python API
  cpp/arcticdb/python/python_module.cpp
Labels: patch

#2526 Do not crash when recursively normalizing dictionaries containing non-str keys
  python/arcticdb/flattener.py
  python/tests/unit/arcticdb/version_store/test_recursive_normalizers.py
Labels: patch

#2512 conda-build: Remove workarounds in specification
  environment-dev.yml
Labels: dependencies, patch

#2530 Update benchmarks.json after changing a benchmark source code
  python/.asv/results/benchmarks.json
Labels: patch, no-release-notes

#2522 Enhancement/9288960436/arrow support for reading sparse float columns
  cpp/arcticdb/column_store/column.cpp
  cpp/arcticdb/pipeline/read_frame.cpp
  cpp/arcticdb/util/sparse_utils.cpp
  cpp/arcticdb/util/sparse_utils.hpp
  python/tests/unit/arcticdb/version_store/test_arrow.py
Labels: patch, no-release-notes
