Repository man-group/ArcticDB, pull requests merged in 2025-04, with the labels that each got.

#2264 Update version constants to replace Sync and Backup IDs
  cpp/arcticdb/version/version_constants.hpp
Labels: patch

#2281 Rollback to last known working CMake version to fix windows builds
  .github/workflows/build_steps.yml
Labels: patch

#2279 Use new name for rc's and fix docs building
  .github/workflows/automated_release.calculate_next_version.yml
  .github/workflows/automated_release.create_developmental_release.yml
  .github/workflows/automated_release.create_release_branch.yml
  .github/workflows/automated_release.full_version_cron.yml
  .github/workflows/automated_release.rc_version.yml
  .github/workflows/build.yml
  .github/workflows/build_docs_on_release.yml
  build_tooling/change_log.json
Labels: patch, no-release-notes

#2280 Rename RecreateVersionId and RefreshVersionId to RecreateSymbolId and RefreshSymbolId for clarity
  cpp/arcticdb/version/version_constants.hpp
Labels: patch

#2289 Fix publishing of rc
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: patch

#2255 GCP real storage tests
  .github/actions/set_persistent_storage_env_vars/action.yml
  .github/workflows/build.yml
  .github/workflows/build_steps.yml
  build_tooling/parallel_test.sh
  cpp/arcticdb/storage/storage_factory.cpp
  pyproject.toml
  python/arcticdb/storage_fixtures/s3.py
  python/arcticdb/util/utils.py
  python/tests/compat/arcticdb/test_lib_naming.py
  python/tests/conftest.py
  python/tests/enduser/__init__.py
  python/tests/enduser/test_authentication.py
  python/tests/hypothesis/arcticdb/test_append.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/test_arctic_batch.py
  python/tests/integration/arcticdb/test_arctic_library_management.py
  python/tests/integration/arcticdb/test_finalize_staged_data.py
  python/tests/integration/arcticdb/test_persistent_storage.py
  python/tests/integration/arcticdb/test_read_batch_more.py
  python/tests/integration/arcticdb/test_storage_lock.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_categorical.py
  python/tests/integration/arcticdb/version_store/test_dedup.py
  python/tests/integration/arcticdb/version_store/test_deletion.py
  python/tests/integration/arcticdb/version_store/test_metadata_support.py
  python/tests/integration/arcticdb/version_store/test_pandas_support.py
  python/tests/integration/arcticdb/version_store/test_snapshot.py
  python/tests/integration/arcticdb/version_store/test_symbol_list.py
  python/tests/integration/arcticdb/version_store/test_symbol_sizes.py
  python/tests/integration/arcticdb/version_store/test_update_with_date_range.py
  python/tests/integration/toolbox/test_library_tool.py
  python/tests/nonreg/arcticdb/version_store/test_nonreg_specific.py
  python/tests/stress/arcticdb/version_store/test_deallocation.py
  python/tests/stress/arcticdb/version_store/test_long_running.py
  python/tests/stress/arcticdb/version_store/test_stress_delete.py
  python/tests/stress/arcticdb/version_store/test_stress_dynamic_bucketize.py
  python/tests/unit/arcticdb/version_store/test_parallel.py
  python/tests/unit/arcticdb/version_store/test_recursive_normalizers.py
  python/tests/unit/arcticdb/version_store/test_sort.py
  python/tests/util/mark.py
  python/tests/util/storage_test.py
Labels: enhancement, patch

#2296 Update build_steps.yml to handle better absence of parameter
  .github/workflows/build_steps.yml
Labels: patch

#2300 Update build_steps.yml fix condition
  .github/workflows/analysis_workflow.yml
  .github/workflows/benchmark_commits.yml
  .github/workflows/build_steps.yml
Labels: patch

#2301 Bugfix 8873431775: Fix NFS-backed storage sharding when deleting objects
  cpp/arcticdb/storage/s3/nfs_backed_storage.cpp
  python/tests/nonreg/arcticdb/version_store/test_nonreg_specific.py
Labels: bug, patch

#2287 Remove python conda pin
  environment_unix.yml
Labels: patch

#2312 Replace moto import with one compatible with moto 5.0
  python/arcticdb/storage_fixtures/s3.py
Labels: minor

#2275 Add warning when integer types are promoted to float during aggregations with dynamic schema.
  cpp/arcticdb/codec/python_bindings.cpp
  cpp/arcticdb/log/log.cpp
  cpp/arcticdb/processing/unsorted_aggregation.cpp
  python/tests/unit/arcticdb/version_store/test_aggregation.py
Labels: patch

#2298 Fix nfs storage tests and bugs in nfs storage
  cpp/arcticdb/storage/s3/nfs_backed_storage.cpp
  python/arcticdb/adapters/s3_library_adapter.py
  python/arcticdb/storage_fixtures/s3.py
  python/tests/conftest.py
Labels: patch

#2299 Change CMake version so that coverity static analysis builds don't crash
  .github/workflows/static_analysis.yml
Labels: patch

#2311 Update s3.py moto*.create_fixture - add retry attempts
  python/arcticdb/storage_fixtures/s3.py
Labels: patch

#2321 Refactor to_atom and to_ref to properly use forwarding references
  cpp/arcticdb/async/test/test_async.cpp
  cpp/arcticdb/entity/variant_key.hpp
  cpp/arcticdb/pipeline/index_utils.hpp
  cpp/arcticdb/storage/storage_utils.cpp
  cpp/arcticdb/stream/stream_utils.hpp
  cpp/arcticdb/util/test/test_key_utils.cpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/test/test_version_store.cpp
  cpp/arcticdb/version/version_core.cpp
  cpp/arcticdb/version/version_utils.cpp
  cpp/arcticdb/version/version_utils.hpp
Labels: patch

#2327 ci: Benchmark workflow adaptations
  .github/workflows/benchmark_commits.yml
Labels: patch

#2323 Fix pr getting action
  .github/workflows/automated_release.calculate_next_version.yml
  .github/workflows/build_docs_on_release.yml
  .github/workflows/publish.yml
  build_tooling/change_log.json
Labels: patch

#2328 conda-build: Extend development environment for Windows
  .github/workflows/build_with_conda.yml
  asv.conf.json
  docs/mkdocs/docs/technical/contributing.md
  environment-dev.yml
Labels: patch

#2333 Increase tolerance to arithmetic mismatches with Pandas with floats
  python/arcticdb/util/test.py
Labels: patch

#2332 Support MSVC 19.29
  cpp/arcticdb/entity/metrics.cpp
  cpp/arcticdb/entity/native_tensor.hpp
  cpp/arcticdb/processing/operation_dispatch_binary.hpp
  cpp/arcticdb/processing/operation_dispatch_unary.hpp
  cpp/arcticdb/stream/merge.hpp
  cpp/arcticdb/version/python_bindings.cpp
Labels: patch

#2320 Fix race conditions on the None object refcount during a multithreaded read
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/column_store/column_utils.hpp
  cpp/arcticdb/pipeline/frame_utils.hpp
  cpp/arcticdb/python/python_handler_data.hpp
  cpp/arcticdb/python/python_handlers.cpp
  cpp/arcticdb/python/python_module.cpp
  cpp/arcticdb/python/python_strings.cpp
  cpp/arcticdb/python/python_strings.hpp
  cpp/arcticdb/python/python_to_tensor_frame.cpp
  cpp/arcticdb/python/python_types.hpp
  cpp/arcticdb/python/python_utils.cpp
  cpp/arcticdb/python/python_utils.hpp
  cpp/arcticdb/storage/python_bindings.cpp
  cpp/arcticdb/util/gil_safe_py_none.cpp
  cpp/arcticdb/util/gil_safe_py_none.hpp
  cpp/arcticdb/version/test/test_sparse.cpp
  cpp/arcticdb/version/version_store_api.cpp
Labels: patch

#2319 Timeseries defrag function
  python/arcticdb/util/defrag_timeseries.py
  python/tests/unit/arcticdb/test_defrag_timeseries.py
Labels: patch

#2326 initial version fix for GCP
  python/arcticdb/storage_fixtures/s3.py
Labels: patch

#2288 Skip azurite api check
  python/arcticdb/storage_fixtures/azure.py
Labels: patch
