Repository man-group/ArcticDB, pull requests merged in 2025-06, with the labels that each got.

#2380 Fix link to the SL caching docs in warning
  cpp/arcticdb/version/symbol_list.cpp
Labels: bug, patch

#2383 Fix moto teardown rare problem
  python/arcticdb/storage_fixtures/s3.py
Labels: patch

#2386 Customizable Run conda tests workflow
  .github/workflows/build_with_conda.yml
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
Labels: patch

#2396 Fix windows STS roles creation
  .github/actions/set_persistent_storage_env_vars/action.yml
  .github/workflows/build_steps.yml
Labels: patch

#2392 9220057136: Allow block manager consolidation in Pandas < 2
  python/arcticdb/version_store/_normalization.py
  python/arcticdb/version_store/library.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
Labels: patch

#2400 Drop support for Python 3.7 and fix CI
  .github/workflows/README.md
  .github/workflows/analysis_workflow.yml
  .github/workflows/build.yml
  .github/workflows/installation_tests.yml
  README.md
  docker/Dockerfile
  docker/Dockerfile_clang
  docs/mkdocs/docs/index.md
  pyproject.toml
  python/arcticdb/storage_fixtures/s3.py
  python/arcticdb/util/utils.py
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
  python/tests/util/mark.py
  setup.cfg
  setup.py
Labels: patch

#2391 ci: Benchmark workflow adaptations (continued)
  .github/workflows/analysis_workflow.yml
Labels: patch

#2403 Remove arcticdb package dependencies on tests and do checks during build
  .github/workflows/build_with_conda.yml
  build_tooling/checks.sh
  python/arcticdb/storage_fixtures/utils.py
  python/arcticdb/util/marks.py
  python/arcticdb/util/test.py
  python/tests/util/mark.py
Labels: patch

#2404 Bugfix/9256801170/memory over allocation when reading shorts dfs
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/column_store/chunked_buffer.cpp
  cpp/arcticdb/column_store/chunked_buffer.hpp
  cpp/arcticdb/column_store/column.cpp
  cpp/arcticdb/column_store/test/test_chunked_buffer.cpp
  cpp/arcticdb/pipeline/frame_utils.hpp
  cpp/arcticdb/pipeline/pipeline_utils.hpp
  cpp/arcticdb/pipeline/string_reducers.hpp
  cpp/arcticdb/util/buffer.hpp
  cpp/arcticdb/util/cursored_buffer.hpp
  cpp/arcticdb/util/sparse_utils.hpp
  cpp/arcticdb/util/test/test_bitmagic.cpp
Labels: bug, patch

#2410 fixed asv benchmark.json file
  python/.asv/results/benchmarks.json
Labels: patch

#2408 Apply perf improvements from pydata talk
  cpp/arcticdb/column_store/column.hpp
  cpp/arcticdb/processing/test/benchmark_projection.cpp
Labels: patch, performance

#2405 Enhancement 9351235967: Support projecting a column of constant values
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/processing/expression_context.hpp
  cpp/arcticdb/processing/test/test_output_schema_ast_validity.cpp
  python/arcticdb/version_store/processing.py
  python/tests/unit/arcticdb/version_store/test_lazy_dataframe.py
  python/tests/unit/arcticdb/version_store/test_projection.py
Labels: enhancement, minor

#2414 Validate staged data symbol names
  cpp/arcticdb/stream/incompletes.cpp
  cpp/arcticdb/stream/incompletes.hpp
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_parallel.py
Labels: patch

#2398 Test for test_admin_tools.py::test_get_sizes_for_symbol flakyness
  .github/workflows/build_steps.yml
  python/arcticdb/storage_fixtures/azure.py
  python/tests/integration/arcticdb/test_admin_tools.py
Labels: patch

#2415 Validate snapshot names
  cpp/arcticdb/util/error_code.hpp
  cpp/arcticdb/util/name_validation.cpp
  cpp/arcticdb/util/name_validation.hpp
  cpp/arcticdb/version/python_bindings.cpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_store_api.hpp
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_unicode.py
Labels: patch

#2417 Batch restore version with timestamp as_of
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/version_map_batch_methods.hpp
  cpp/arcticdb/version/version_tasks.hpp
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
Labels: patch

#2428 fix problem with pandas 1.0.5 and empty dataframe comparison
  python/arcticdb/util/test.py
Labels: patch
