Repository man-group/ArcticDB, pull requests merged in 2025-03, with the labels that each got.

#2223 Add pin for fmt in conda
  environment_unix.yml
Labels: patch

#2199 Memray tests for memory leaks for head() and tail()
  python/arcticdb/util/utils.py
  python/tests/conftest.py
  python/tests/stress/arcticdb/version_store/test_mem_leaks.py
Labels: patch

#2220 Release the GIL during parallel writes to avoid deadlock
  cpp/arcticdb/version/local_versioned_engine.cpp
  python/tests/unit/arcticdb/version_store/test_write.py
Labels: bug, patch

#2218 Fix and test arcticdb reading streaming data
  cpp/arcticdb/pipeline/read_pipeline.hpp
  cpp/arcticdb/version/version_core.cpp
  python/tests/compat/arcticdb/test_compatibility.py
  python/tests/unit/arcticdb/version_store/test_incompletes.py
Labels: patch

#2209 Return correct timestamp in the VersionItem returned by write when recursive normalizers are used
  cpp/arcticdb/storage/s3/s3_client_wrapper.cpp
  cpp/arcticdb/version/version_core.cpp
  cpp/arcticdb/version/version_store_api.cpp
  cpp/arcticdb/version/version_utils.cpp
  cpp/arcticdb/version/version_utils.hpp
  python/arcticdb/util/test.py
  python/arcticdb/version_store/_store.py
  python/tests/compat/arcticdb/test_compatibility.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/unit/arcticdb/version_store/test_recursive_normalizers.py
Labels: patch

#2226 Update aws.md with errors
  docs/mkdocs/docs/aws.md
Labels: patch

#2206 Tolerate keys being deleted while scanning object sizes
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/async/async_store.hpp
  cpp/arcticdb/async/batch_read_args.hpp
  cpp/arcticdb/pipeline/read_frame.cpp
  cpp/arcticdb/storage/test/in_memory_store.hpp
  cpp/arcticdb/stream/stream_source.hpp
  cpp/arcticdb/toolbox/storage_mover.hpp
  cpp/arcticdb/util/test/test_folly.cpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  python/tests/integration/arcticdb/version_store/test_symbol_sizes.py
Labels: patch

#2212 Fix regression when writing combination of np.NaN and None
  cpp/arcticdb/pipeline/write_frame.cpp
  cpp/arcticdb/python/python_to_tensor_frame.cpp
  python/tests/hypothesis/arcticdb/test_sort_merge.py
  python/tests/unit/arcticdb/version_store/test_write.py
Labels: patch

#2229 Update docs for sts auth
  docs/mkdocs/docs/api/arctic_uri.md
  docs/mkdocs/docs/aws.md
Labels: documentation, minor

#2237 Update test_mem_leaks.py - increase memory limit
  python/tests/stress/arcticdb/version_store/test_mem_leaks.py
Labels: patch

#2239 Fix test_chunks_the_same flakiness
  python/tests/unit/arcticdb/version_store/test_parallel.py
Labels: flaky test, patch

#2224 Testing for unicode handling across our API
  python/arcticdb/util/test.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_symbol_list.py
  python/tests/stress/arcticdb/version_store/test_mem_leaks.py
  python/tests/unit/arcticdb/version_store/test_append.py
  python/tests/unit/arcticdb/version_store/test_sort.py
  python/tests/unit/arcticdb/version_store/test_string_dedup.py
  python/tests/unit/arcticdb/version_store/test_unicode.py
  python/tests/unit/arcticdb/version_store/test_update.py
  python/tests/unit/arcticdb/version_store/test_write.py
Labels: patch

#2240 Use tag 0.0.0.dev0 for dev wheels
  setup.cfg
Labels: patch

#2246 Ignore pr in changelog
  build_tooling/change_log.json
Labels: patch, no-release-notes

#2230 Automatically build docs on release
  .github/workflows/build_docs_on_release.yml
  .github/workflows/docs_build.yml
Labels: patch

#2247 Fix branch creation
  .github/workflows/automated_release.calculate_next_version.yml
Labels: patch, no-release-notes

#2233 Enhancement/8561507350/precompute output schema from processing
  cpp/arcticdb/CMakeLists.txt
  cpp/arcticdb/entity/stream_descriptor.hpp
  cpp/arcticdb/processing/aggregation_interface.hpp
  cpp/arcticdb/processing/clause.cpp
  cpp/arcticdb/processing/clause.hpp
  cpp/arcticdb/processing/expression_context.hpp
  cpp/arcticdb/processing/expression_node.cpp
  cpp/arcticdb/processing/expression_node.hpp
  cpp/arcticdb/processing/operation_types.hpp
  cpp/arcticdb/processing/sorted_aggregation.hpp
  cpp/arcticdb/processing/test/test_clause.cpp
  cpp/arcticdb/processing/test/test_output_schema_aggregator_types.cpp
  cpp/arcticdb/processing/test/test_output_schema_ast_validity.cpp
  cpp/arcticdb/processing/test/test_output_schema_basic.cpp
  cpp/arcticdb/processing/test/test_parallel_processing.cpp
  cpp/arcticdb/processing/unsorted_aggregation.cpp
  cpp/arcticdb/processing/unsorted_aggregation.hpp
  cpp/arcticdb/util/test/generators.hpp
Labels: patch

#2235 Fix convert_int_to_float in compact_incomplete V1 library API method
  cpp/arcticdb/entity/merge_descriptors.cpp
  cpp/arcticdb/entity/merge_descriptors.hpp
  cpp/arcticdb/stream/incompletes.cpp
  cpp/arcticdb/stream/segment_aggregator.hpp
  cpp/arcticdb/version/schema_checks.cpp
  cpp/arcticdb/version/schema_checks.hpp
  cpp/arcticdb/version/version_core.cpp
  cpp/arcticdb/version/version_core.hpp
  python/tests/unit/arcticdb/version_store/test_parallel.py
Labels: patch

#2244 Slightly wider tolerance to arithmetic mismatches with Pandas with floats
  python/arcticdb/util/test.py
Labels: patch

#2248 Get object sizes based on S3's ListObjects output (just with scan_object_sizes() to start with)
  cpp/arcticdb/async/async_store.hpp
  cpp/arcticdb/async/tasks.hpp
  cpp/arcticdb/storage/library.hpp
  cpp/arcticdb/storage/s3/detail-inl.hpp
  cpp/arcticdb/storage/s3/nfs_backed_storage.cpp
  cpp/arcticdb/storage/s3/nfs_backed_storage.hpp
  cpp/arcticdb/storage/s3/s3_client_impl.cpp
  cpp/arcticdb/storage/s3/s3_client_interface.hpp
  cpp/arcticdb/storage/s3/s3_storage.cpp
  cpp/arcticdb/storage/s3/s3_storage.hpp
  cpp/arcticdb/storage/storage.hpp
  cpp/arcticdb/storage/storages.hpp
  cpp/arcticdb/storage/test/in_memory_store.hpp
  cpp/arcticdb/stream/stream_source.hpp
  cpp/arcticdb/version/local_versioned_engine.cpp
  cpp/arcticdb/version/local_versioned_engine.hpp
  cpp/arcticdb/version/python_bindings.cpp
  python/tests/integration/arcticdb/version_store/test_symbol_sizes.py
  python/tests/unit/arcticdb/version_store/test_parallel.py
Labels: patch

#2222 Add bounds check for empty tensors and enhance tests for numpy slicing
  cpp/arcticdb/entity/native_tensor.hpp
  python/tests/unit/arcticdb/version_store/test_normalization.py
Labels: patch

#2215 Improve CI run time
  .github/workflows/build.yml
  .github/workflows/build_steps.yml
  cpp/CMakePresets.json
  python/arcticdb/arctic.py
  python/arcticdb/storage_fixtures/api.py
  python/arcticdb/storage_fixtures/lmdb.py
  python/arcticdb/storage_fixtures/mongo.py
  python/arcticdb/storage_fixtures/s3.py
  python/arcticdb/util/test.py
  python/tests/compat/arcticdb/test_compatibility.py
  python/tests/compat/arcticdb/test_lib_naming.py
  python/tests/conftest.py
  python/tests/hypothesis/arcticdb/test_append.py
  python/tests/integration/arcticdb/test_arctic.py
  python/tests/integration/arcticdb/test_arctic_batch.py
  python/tests/integration/arcticdb/test_arctic_library_management.py
  python/tests/integration/arcticdb/test_arctic_move_storage.py
  python/tests/integration/arcticdb/test_in_memory.py
  python/tests/integration/arcticdb/test_lmdb.py
  python/tests/integration/arcticdb/test_s3.py
  python/tests/integration/arcticdb/version_store/test_basic_version_store.py
  python/tests/integration/arcticdb/version_store/test_snapshot.py
  python/tests/integration/arcticdb/version_store/test_symbol_list.py
  python/tests/integration/toolbox/test_storage_mover.py
  python/tests/scripts/test_update_storage.py
  python/tests/stress/arcticdb/version_store/test_large_df.py
  python/tests/stress/arcticdb/version_store/test_mem_leaks.py
  python/tests/stress/arcticdb/version_store/test_stress_delete.py
  python/tests/stress/arcticdb/version_store/test_stress_generated.py
  python/tests/stress/arcticdb/version_store/test_stress_indexing.py
  python/tests/stress/arcticdb/version_store/test_stress_version_map_compact.py
  python/tests/stress/arcticdb/version_store/test_stress_versions.py
  python/tests/unit/arcticdb/test_errors.py
  python/tests/unit/arcticdb/version_store/test_fork.py
  python/tests/unit/arcticdb/version_store/test_parallel.py
  python/tests/unit/arcticdb/version_store/test_sort.py
  python/tests/util/mark.py
Labels: patch

#2250 Add more logging to compat tests
  python/arcticdb/util/venv.py
Labels: patch

#2232 Accept strings for the mode when finalizing staged data
  python/arcticdb/version_store/library.py
  python/tests/integration/arcticdb/test_finalize_staged_data.py
  python/tests/unit/arcticdb/version_store/test_api.py
Labels: patch

#2256 Use `is` for `None`
  python/arcticdb/version_store/library.py
Labels: patch

#2253 Correctly handle `zoneinfo` timezones
  python/arcticdb/version_store/_normalization.py
  python/tests/compat/arcticdb/test_compatibility.py
  python/tests/integration/arcticdb/version_store/test_metadata_support.py
  python/tests/unit/arcticdb/version_store/test_normalization.py
  python/tests/util/mark.py
Labels: patch

#2254 Fix for STS support
  cpp/arcticdb/storage/common.hpp
  cpp/arcticdb/storage/python_bindings.cpp
  cpp/arcticdb/storage/s3/s3_settings.hpp
  python/arcticdb/adapters/__init__.py
  python/arcticdb/adapters/gcpxml_library_adapter.py
  python/arcticdb/adapters/s3_library_adapter.py
  python/arcticdb/version_store/helper.py
  python/tests/conftest.py
  python/tests/unit/arcticdb/test_library_adapters.py
Labels: patch

#2257 Improve error message in case of network error
  cpp/arcticdb/storage/s3/detail-inl.hpp
  python/tests/integration/arcticdb/test_s3.py
Labels: patch

#2262 Fix the perfect forwarding in variant_match
  cpp/arcticdb/entity/key.hpp
  cpp/arcticdb/entity/types.hpp
  cpp/arcticdb/storage/s3/s3_storage.hpp
  cpp/arcticdb/util/buffer.hpp
  cpp/arcticdb/util/variant.hpp
  cpp/arcticdb/version/version_core.cpp
Labels: patch

#2271 Licensing doc
  README.md
Labels: documentation, patch, no-release-notes

#2272 Remove fmt pin on conda
  environment_unix.yml
Labels: minor

#2269 Create a dev image that uses clang as a compiler and use it for the Linux C++ tests
  .github/workflows/build.yml
  .github/workflows/build_steps.yml
  .github/workflows/dev_docker_image.yml
  docker/Dockerfile_clang
  docker/build_clang.sh
  python/tests/conftest.py
Labels: patch

#2273 Fix slack build failure bad link
  .github/workflows/failure_notification.yaml
Labels: patch

#2276 Backport fmt pin removal on conda to v5.3.1
  environment_unix.yml
Labels: patch
